---
title: "gettingData"
author: "Katya Katsy"
date: "12/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Exploration

```{r}
health_df <- read.csv("heart_disease_health_indicators.csv")
health_df <- read.csv("new_data1.csv")
head(health_df)
```
```{r}
names(health_df)
```


```{r}
summary(health_df)
```

```{r}
str(health_df)
```

```{r}
colSums(is.na(health_df))
```

```{r}
table(health_df$HeartDiseaseorAttack)
true_attack = nrow(health_df[health_df$HeartDiseaseorAttack,])
false_attack = nrow(health_df[!health_df$HeartDiseaseorAttack,])
cat("Percentage of true: ", true_attack*100/(true_attack+false_attack), "%")
```

```{r}
# Non-boolean: age, BMI, MentHlth, GenHlth, Education, Income
par(mfrow=c(2,3))

barplot(t(prop.table(table(health_df$HeartDiseaseorAttack))), ylab="Percent", xlab="Heart disease or attack", col="dodgerblue3")

barplot(t(prop.table(table(health_df$AnyHealthcare))), ylab="Percent", xlab="Healthcare", col="dodgerblue3")

barplot(t(prop.table(table(health_df$HighBP))), ylab="Percent", xlab="High blood pressure", col="dodgerblue3")

barplot(t(prop.table(table(health_df$BMI))), ylab="Percent", xlab="BMI", col="dodgerblue3")

barplot(t(prop.table(table(health_df$Education))), ylab="Percent", xlab="Education level", col="dodgerblue3")

barplot(t(prop.table(table(health_df$HighBP))), ylab="Percent", xlab="High blood pressure", col="dodgerblue3")

barplot(t(prop.table(table(health_df$HighChol))), ylab="Percent", xlab="High cholesterol", col="dodgerblue3")

barplot(t(prop.table(table(health_df$Income))), ylab="Percent", xlab="Income category", col="dodgerblue3")


barplot(t(prop.table(table(health_df$PhysActivity))), ylab="Percent", xlab="Physical activity level", col="dodgerblue3")


barplot(t(prop.table(table(health_df$Sex))), ylab="Percent", xlab="Sex", col="dodgerblue3")


barplot(t(prop.table(table(health_df$Smoker))), ylab="Percent", xlab="Smoker", col="dodgerblue3")

```

```{r}
# histogram + frequency tables for data
# add as subplots of single plot

```

